spring.datasource.url=jdbc:postgresql://localhost:5432/db_video
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.main.banner-mode=off
app.thumbnails.dir=D:/workspaces/demo/thumbnails
server.port=8081