spring.datasource.url=jdbc:postgresql://localhost:5432/monappdb
spring.datasource.username=monuser
spring.datasource.password=motdepassefort
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.main.banner-mode=off
app.thumbnails.dir=/home/ubuntu/demo/thumbnails
app.videos.dir=/home/ubuntu/demo/videos
server.port=8081
spring.flyway.enabled=false
